import type { Product, Category } from "@/features/orders/types/index";

export const PRODUCTS: Product[] = [
    {
        id: 1,
        name: "Pastel de Chocolate",
        price: 450,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
    },
    {
        id: 2,
        name: "Cheesecake de Fresa",
        price: 480,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50",
    },
    {
        id: 3,
        name: "Pastel de Zanahoria",
        price: 420,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729",
    },
    {
        id: 4,
        name: "Porción de Red Velvet",
        price: 65,
        category: "Pasteles y Postres",
        subcategory: "Porciones",
        image: "https://images.unsplash.com/photo-1616541823729-00fe0aacd32c",
    },
    {
        id: 5,
        name: "Porción Pie de Limón",
        price: 55,
        category: "Pasteles y Postres",
        subcategory: "Porciones",
        image: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13",
    },
    {
        id: 6,
        name: "Tiramisú Individual",
        price: 70,
        category: "Pasteles y Postres",
        subcategory: "Postres Individuales",
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9",
    },
    {
        id: 7,
        name: "Muffin de Arándanos",
        price: 35,
        category: "Pasteles y Postres",
        subcategory: "Postres Individuales",
        image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa",
    },
    {
        id: 20,
        name: "Tres Leches (Grande)",
        price: 550,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1562762419-7f55b172a514",
    },
    {
        id: 21,
        name: "Selva Negra",
        price: 600,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1536551833446-ad87333e6604",
    },
    {
        id: 22,
        name: "Porción Tres Leches",
        price: 75,
        category: "Pasteles y Postres",
        subcategory: "Porciones",
        image: "https://images.unsplash.com/photo-1549419137-b6f3c1b01783",
    },
    {
        id: 23,
        name: "Tartaleta de Frutas",
        price: 45,
        category: "Pasteles y Postres",
        subcategory: "Postres Individuales",
        image: "https://images.unsplash.com/photo-1560180474-e8563fd75bab",
    },
    {
        id: 24,
        name: "Mousse de Chocolate",
        price: 55,
        category: "Pasteles y Postres",
        subcategory: "Postres Individuales",
        image: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3",
    },
    {
        id: 25,
        name: "Cupcake de Vainilla",
        price: 30,
        category: "Pasteles y Postres",
        subcategory: "Postres Individuales",
        image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcf8",
    },
    {
        id: 43,
        name: "Pastel de Vainilla",
        price: 400,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b",
    },
    {
        id: 44,
        name: "Torta Helada",
        price: 520,
        category: "Pasteles y Postres",
        subcategory: "Pasteles Enteros",
        image: "https://images.unsplash.com/photo-1560008581-2cf30c0a2b73",
    },
    {
        id: 45,
        name: "Porción de Torta Helada",
        price: 70,
        category: "Pasteles y Postres",
        subcategory: "Porciones",
        image: "https://images.unsplash.com/photo-1607478923763-68547e0a16f6",
    },
    {
        id: 46,
        name: "Profiteroles (3 und)",
        price: 50,
        category: "Pasteles y Postres",
        subcategory: "Postres Individuales",
        image: "https://images.unsplash.com/photo-1610492486313-275193c9493d",
    },

    {
        id: 8,
        name: "Croissant",
        price: 30,
        category: "Panadería y Repostería",
        subcategory: "Panes",
        image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a",
    },
    {
        id: 9,
        name: "Pan de Ajo",
        price: 25,
        category: "Panadería y Repostería",
        subcategory: "Panes",
        image: "https://images.unsplash.com/photo-1573140247632-f84660f67126",
    },
    {
        id: 10,
        name: "Galletas de Avena (6 und)",
        price: 60,
        category: "Panadería y Repostería",
        subcategory: "Galletas",
        image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e",
    },
    {
        id: 11,
        name: "Dona Glaseada",
        price: 25,
        category: "Panadería y Repostería",
        subcategory: "Rosquillas",
        image: "https://images.unsplash.com/photo-1551024601-bec78d8d590d",
    },
    {
        id: 12,
        name: "Macarons (4 und)",
        price: 80,
        category: "Panadería y Repostería",
        subcategory: "Repostería Variada",
        image: "https://images.unsplash.com/photo-1558326567-98ae2405596b",
    },
    {
        id: 26,
        name: "Baguette Artesanal",
        price: 40,
        category: "Panadería y Repostería",
        subcategory: "Panes",
        image: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04",
    },
    {
        id: 27,
        name: "Hogaza de Masa Madre",
        price: 85,
        category: "Panadería y Repostería",
        subcategory: "Panes",
        image: "https://images.unsplash.com/photo-1585476644391-ab8e050bbb04",
    },
    {
        id: 28,
        name: "Galletas Chispas Chocolate (6)",
        price: 70,
        category: "Panadería y Repostería",
        subcategory: "Galletas",
        image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e",
    },
    {
        id: 29,
        name: "Polvorones (Bolsa)",
        price: 50,
        category: "Panadería y Repostería",
        subcategory: "Galletas",
        image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e",
    },
    {
        id: 30,
        name: "Dona de Chocolate",
        price: 30,
        category: "Panadería y Repostería",
        subcategory: "Rosquillas",
        image: "https://images.unsplash.com/photo-1551106652-a5bcf4b29e5d",
    },
    {
        id: 31,
        name: "Churros con Azúcar (4 und)",
        price: 40,
        category: "Panadería y Repostería",
        subcategory: "Rosquillas",
        image: "https://images.unsplash.com/photo-1624371414361-e670edf4898d",
    },
    {
        id: 32,
        name: "Brownie con Nuez",
        price: 45,
        category: "Panadería y Repostería",
        subcategory: "Repostería Variada",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c",
    },
    {
        id: 33,
        name: "Rollo de Canela",
        price: 50,
        category: "Panadería y Repostería",
        subcategory: "Repostería Variada",
        image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812",
    },
    {
        id: 34,
        name: "Pastelito de Piña",
        price: 25,
        category: "Panadería y Repostería",
        subcategory: "Repostería Variada",
        image: "https://images.unsplash.com/photo-1623653199852-5df58344c21f",
    },
    {
        id: 47,
        name: "Pan de Banano (Rebanada)",
        price: 35,
        category: "Panadería y Repostería",
        subcategory: "Panes",
        image: "https://images.unsplash.com/photo-1589967213689-343331388934",
    },
    {
        id: 48,
        name: "Galletas de Mantequilla (Bolsa)",
        price: 55,
        category: "Panadería y Repostería",
        subcategory: "Galletas",
        image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e",
    },
    {
        id: 49,
        name: "Berlinesa con Manjar",
        price: 35,
        category: "Panadería y Repostería",
        subcategory: "Rosquillas",
        image: "https://images.unsplash.com/photo-1621742133433-03c1550a1b24",
    },
    {
        id: 50,
        name: "Milhojas",
        price: 50,
        category: "Panadería y Repostería",
        subcategory: "Repostería Variada",
        image: "https://images.unsplash.com/photo-1587122569949-ae07b31a52f3",
    },
    {
        id: 51,
        name: "Alfajor de Maicena",
        price: 25,
        category: "Panadería y Repostería",
        subcategory: "Repostería Variada",
        image: "https://images.unsplash.com/photo-1622926421314-5943719a9741",
    },

    {
        id: 13,
        name: "Coca-Cola (12 onz)",
        price: 30,
        category: "Bebidas",
        subcategory: "Sodas",
        image: "https://images.unsplash.com/photo-1554866585-cd94860890b7",
    },
    {
        id: 14,
        name: "Sprite (12 onz)",
        price: 30,
        category: "Bebidas",
        subcategory: "Sodas",
        image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3",
    },
    {
        id: 15,
        name: "Limonada con Hierbabuena",
        price: 45,
        category: "Bebidas",
        subcategory: "Refrescos Naturales",
        image: "https://images.unsplash.com/photo-1623593689592-a265332f3a2a",
    },
    {
        id: 16,
        name: "Té de Jamaica",
        price: 40,
        category: "Bebidas",
        subcategory: "Refrescos Naturales",
        image: "https://images.unsplash.com/photo-1627486229433-5567154244a3",
    },
    {
        id: 17,
        name: "Cappuccino",
        price: 50,
        category: "Bebidas",
        subcategory: "Cafés",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d",
    },
    {
        id: 18,
        name: "Espresso",
        price: 35,
        category: "Bebidas",
        subcategory: "Cafés",
        image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04",
    },
    {
        id: 19,
        name: "Red Bull",
        price: 70,
        category: "Bebidas",
        subcategory: "Energizantes",
        image: "https://images.unsplash.com/photo-1619157999800-a79b08543a38",
    },
    {
        id: 35,
        name: "Agua Mineral",
        price: 25,
        category: "Bebidas",
        subcategory: "Sodas",
        image: "https://images.unsplash.com/photo-1563212624-a7455d31191c",
    },
    {
        id: 36,
        name: "Fanta Naranja (12 onz)",
        price: 30,
        category: "Bebidas",
        subcategory: "Sodas",
        image: "https://images.unsplash.com/photo-1624517452488-04869289c4ca",
    },
    {
        id: 37,
        name: "Cacao con Leche",
        price: 50,
        category: "Bebidas",
        subcategory: "Refrescos Naturales",
        image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574",
    },
    {
        id: 38,
        name: "Jugo de Naranja",
        price: 45,
        category: "Bebidas",
        subcategory: "Refrescos Naturales",
        image: "https://images.unsplash.com/photo-1613478223719-2ab802602423",
    },
    {
        id: 39,
        name: "Batido de Fresa",
        price: 60,
        category: "Bebidas",
        subcategory: "Refrescos Naturales",
        image: "https://images.unsplash.com/photo-1553177595-4de2bb0842b9",
    },
    {
        id: 40,
        name: "Latte Caramel",
        price: 65,
        category: "Bebidas",
        subcategory: "Cafés",
        image: "https://images.unsplash.com/photo-1599398054066-846f28917f38",
    },
    {
        id: 41,
        name: "Iced Coffee",
        price: 60,
        category: "Bebidas",
        subcategory: "Cafés",
        image: "https://images.unsplash.com/photo-1517701604599-bb29b5c7355c",
    },
    {
        id: 42,
        name: "Monster Energy",
        price: 85,
        category: "Bebidas",
        subcategory: "Energizantes",
        image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97",
    },
    {
        id: 52,
        name: "Jugo de Piña",
        price: 45,
        category: "Bebidas",
        subcategory: "Refrescos Naturales",
        image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba",
    },
    {
        id: 53,
        name: "Americano",
        price: 40,
        category: "Bebidas",
        subcategory: "Cafés",
        image: "https://images.unsplash.com/photo-1507133750040-4a8f570215de",
    },
    {
        id: 54,
        name: "Chocolate Caliente",
        price: 55,
        category: "Bebidas",
        subcategory: "Cafés",
        image: "https://images.unsplash.com/photo-1542990253-a7814f27a22c",
    },
];

export const CATEGORIES_DATA: Category[] = [
    {
        name: "Pasteles y Postres",
        subcategories: ["Pasteles Enteros", "Porciones", "Postres Individuales"],
    },
    {
        name: "Panadería y Repostería",
        subcategories: ["Panes", "Galletas", "Rosquillas", "Repostería Variada"],
    },
    {
        name: "Bebidas",
        subcategories: ["Sodas", "Refrescos Naturales", "Cafés", "Energizantes"],
    },
];